# Generated by Django 5.2.14 on 2026-06-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='couvertures/'),
        ),
    ]
