# Generated by Django 5.2.14 on 2026-06-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
